scripts:
      - name: Configure Flutter SDK Path
        script: |
          # هذه الأسطر تضمن أن السيرفر يعرف مكان Flutter بدقة 100%
          mkdir -p android
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties
          
          # إجبار Gradle على رؤية التغييرات
          export GRADLE_OPTS="-Dorg.gradle.project.flutter.sdk=$FLUTTER_ROOT"
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --no-tree-shake-icons
