scripts:
      - name: Prepare local.properties
        script: |
          mkdir -p android
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          # تنظيف الملفات القديمة ضروري جداً عند تغيير هيكل Gradle
          flutter clean
          flutter build apk --release --no-tree-shake-icons
